{{- if .Values.createService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.nameSpace | default .Release.Namespace | quote }}
spec:
  type: {{ .Values.service.type }}
  ports: 
  - name: {{ .Values.service.ports.name }}
    {{- if .Values.isFrontend }}
    port: {{ (.Values.service.ports.port | default .Values.containerPort) | default 80 }}
    targetPort: {{ (.Values.service.ports.targetPort | default .Values.containerPort) | default 80 }}
    {{- else }}
    port: {{ (.Values.service.ports.port | default .Values.containerPort) | default 8080 }}
    targetPort: {{ (.Values.service.ports.targetPort | default .Values.containerPort) | default 8080 }}
    {{- end }}
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.ports.nodePort)) }}
    nodePort: {{ .Values.service.ports.nodePort }}
    {{- end }}

  {{- if .Values.service.extraPorts }}
  {{- include "common.tplvalues.render" (dict "value" .Values.service.extraPorts "context" $) | nindent 2 }}
  {{- end }}
  selector: 
    app: {{ .Values.name }}
    
  {{- if .Values.service.sessionAffinity }}
  # 会话保持策略
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if and .Values.service.sessionAffinityConfig (eq .Values.service.sessionAffinity "ClientIP") }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- end }}

  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  {{- if .Values.service.externalTrafficPolicy }}
  # 外部流量策略
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- end }}

  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerSourceRanges)) }}
  # 限制可以访问负载均衡器的源IP地址段
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 2 }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  # 负载均衡IP
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}

{{- end }}