apiVersion: v1
entries:
  app1.2:
  - apiVersion: v2
    created: "2024-01-05T14:11:43.413917709+08:00"
    description: nginx服务 或者 jar包 的Helm chart
    digest: 379f01ab7e40bde7290c9b3c2f93988bddc2badb7cf23a2a07906c48412b41b1
    keywords:
    - spring boot
    - java
    - Vue
    - nginx
    maintainers:
    - name: zwx
    name: app1.2
    type: application
    urls:
    - app1.2-1.2.0.tgz
    version: 1.2.0
  app1.3:
  - apiVersion: v2
    created: "2024-01-05T14:11:43.415114167+08:00"
    description: nginx服务 或者 jar包 的Helm chart
    digest: 1470f6af00ddd592b10e1a3c1f27e4c0a5b366c18e580008940dba3ca38af30b
    keywords:
    - spring boot
    - java
    - Vue
    - nginx
    maintainers:
    - name: zwx
    name: app1.3
    type: application
    urls:
    - app1.3-1.3.0.tgz
    version: 1.3.0
generated: "2024-01-05T14:11:43.412579075+08:00"
